---
title: "Recursos sobre Quarto"
---

Desde que **Quarto** se hizo publico con [We don't talk about Quarto](https://www.apreshill.com/blog/2022-04-we-dont-talk-about-quarto/) ha sido un no parar de workshops, posts, etc... En esta página tienes una selección de recursos sobre Quarto.

Obviamente la **principal referencia** es la [web de Quarto](https://quarto.org/): **absolutamente fantástica**!!! En ella hay, entre otras secciones, una [Guide](https://quarto.org/docs/guide/), una [Reference](https://quarto.org/docs/reference/) y una [Gallery](https://quarto.org/docs/gallery/).

<br>

Entre los materiales que he visto sobre Quarto **destacar los siguientes**:


- [AWESOME Quarto](https://github.com/mcanouil/awesome-quarto): un listado muy extenso de recursos Quarto hecho por Mickaël Canouil.

- [Quarto tip a day](http://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/): Un blog de Mine Çetinkaya-Rundel con consejos y tips sobre Quarto.

- [ Get Started with Quarto](https://jthomasmock.github.io/quarto-2hr-webinar/): un workshop de Thomas Mock. El [video](https://youtu.be/yvi5uXQMvu4), y [otro video de 3h](https://www.youtube.com/watch?v=KnwQFph3s94&list=PL4IzsxWztPdmSeucR67EH_8_hzldqYZX4&index=8).

- [Beautiful Reports and Presentations with Quarto](https://thomasmock.quarto.pub/reports-presentations/#/title-slide): un workshop de Thomas Mock. El [video](https://www.youtube.com/watch?v=hbf7Ai3jnxY) y el [repo](https://github.com/jthomasmock/quarto-reporting). 

- [Introducción a RMarkdown, creando reportes con R y Python en RStudio](https://www.youtube.com/watch?v=d8jSN998Mtw): workshop de Renzo Cáceres para LatinR 2022.

- [Making shareable documents with Quarto](https://openscapes.github.io/quarto-website-tutorial/): una web de Openscapes.

- [Quarto/RMarkdown - What’s Different?](https://laderast.github.io/qmd_rmd/#/title-slide): unas slides de Ted Laderas.

- [Rstudio::conf(2022) Playlist](https://www.youtube.com/playlist?list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH):  la presentación en sociedad de Quarto con varias charlas sobre Quarto, [Hello Quarto: Share, Collaborate, Teach, Reimagine](https://www.youtube.com/watch?v=p7Hxu4coDl8&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=4), [Websites & Books & Blogs, oh my! Creating Rich Content with Quarto](https://www.youtube.com/watch?v=A9QRN4cpsDY&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=49), [Quarto for the Curious ](https://www.youtube.com/watch?v=mrvhk2XUfWo&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=55) entre otras.  

-  [Rstudio::conf(2022) Workshops](https://github.com/rstudio-conf-2022): por ejemplo, [Get Started with Quarto](https://github.com/rstudio-conf-2022/get-started-quarto) o [Rmarkdown to Quarto](https://github.com/rstudio-conf-2022/rmd-to-quarto).

- [Reproducible authoring with Quarto](https://www.youtube.com/watch?v=6p4vOKS6Xls): un video de Mine Çetinkaya-Rundel donde se hace evidente las ventajas de Quarto y la utilidad del editor visual de RStudio. Sus slides [aquí](https://mine-cetinkaya-rundel.github.io/2022-repro-toronto/#/title-slide).




<br>

###### Recursos **específicos sobre web/blogs**


- [Quarto - Creating a Blog](https://quarto.org/docs/websites/website-blog.html): documentación oficial.

- [Building a blog with Quarto](https://ivelasq.quarto.pub/building-a-blog-with-quarto/): un workshop de Isabella Velásquez acerca de cómo construir un blog con Quarto. El [repo de los ejercicios](https://github.com/ivelasq/build-your-own-blog-exercises), [video](https://www.youtube.com/watch?v=CVcvXfRyfE0) y [RStudioCloud project]( https://rstudio.cloud/project/4404816).

- [Websites & Books & Blogs, oh my! Creating Rich Content with Quarto](https://www.youtube.com/watch?v=A9QRN4cpsDY&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=49): ponencia de Devin Pastoor en el marco de RStudio::conf(2022).

- [Modifying the Default Quarto Blog Structure](https://www.ericekholm.com/posts/demo-quarto-site/): post de Eric Ekholm 2022. 

- [Creating a Blog with Quarto in 10 Steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/): post de Bea Milz.

- [100 seconds from zero to public site](https://youtube.com/watch?v=t8qtcDyCRFA&t=1s): vídeo de Thomas Mock donde crea una web con Quarto en 100 segundos.

- [Porting a Distill Blog to Quarto](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/): post de Danielle Navarro.
